repos:
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: local
    hooks:
    - id: regenerate-readme
      name: Regenerate README
      language: system
      entry: python README.py
      types: [python]